services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    expose:
      - "80"
    volumes:
      - ./data:/app/data
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - server