services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    network_mode: "host"   # server가 필요한 포트를 그대로 사용
    restart: unless-stopped